version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable-curl
    steps:
      - checkout
      - restore_cache:
          key: downloads
      - run:
          name: Build app
          command: |
            sudo apt-get install -y make libglib2.0-0 libnss3 libxcomposite1 libxcursor1 libxi6 libxtst6 libcups2 libxss1 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libgtk-3-0
            make
      - save_cache:
          key: downloads
          paths:
            - tmp
      - run:
          name: Run tests
          command: make test
      - store_test_results:
          path: reports
      - store_artifacts:
          path: build/chrome/simpljs.zip
          destination: chrome
      - store_artifacts:
          path: build/linux/Simpl.js.tar.gz
          destination: linux
      - store_artifacts:
          path: build/macos/Simpl.js.zip
          destination: macos
      - store_artifacts:
          path: build/windows/Simpl.js.zip
          destination: windows
